export const CONSUMABLE_ITEMS = [
  'Screens',
  'Riser',
  'J-Plugs',
  'Slip Caps',
  'Bottom Caps',
  'Flush Protectors',
  'Above Grade Protectors',
  'Locks',
  'Holeplug',
  'Silica Sand',
  'Stone Mix',
  'Quickgel',
  'Portland/Portland Cement',
  'Benseal',
  'Auger Teeth',
  'Spoon Tips',
  'Concrete',
  'Couplings',
  'Drums',
  'Flushmounts',
  'Geo-probe Liners',
  'Bailers',
  'Well/Pad Locks',
  'Auger Plugs',
  'Other'
];
